#!/bin/sh
# Fetch the pinned Zig toolchain into .tools/ and prepare host shims.
set -eu

ZIG_VERSION=0.14.1
ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
TOOLS="$ROOT/.tools"
INDEX_URL="https://ziglang.org/download/index.json"

uname_s=$(uname -s)
uname_m=$(uname -m)
case "$uname_s-$uname_m" in
Darwin-arm64) zig_plat="aarch64-macos" ;;
Linux-x86_64) zig_plat="x86_64-linux" ;;
Linux-aarch64) zig_plat="aarch64-linux" ;;
Darwin-x86_64) zig_plat="x86_64-macos" ;;
*)
  echo "unsupported host: $uname_s-$uname_m" >&2
  exit 1
  ;;
esac

mkdir -p "$TOOLS" "$TOOLS/bin"

if [ ! -x "$TOOLS/zig-$ZIG_VERSION/zig" ]; then
  meta=$(curl -fsSL "$INDEX_URL" | python3 -c "
import json, sys
info = json.load(sys.stdin)['$ZIG_VERSION']['$zig_plat']
print(info['tarball']); print(info['shasum'])")
  url=$(printf '%s\n' "$meta" | sed -n '1p')
  want=$(printf '%s\n' "$meta" | sed -n '2p')
  tarball="$TOOLS/$(basename "$url")"

  echo "fetching $url"
  curl -fsSL "$url" -o "$tarball"
  if command -v sha256sum >/dev/null 2>&1; then
    got=$(sha256sum "$tarball" | cut -d' ' -f1)
  else
    got=$(shasum -a 256 "$tarball" | cut -d' ' -f1)
  fi
  [ "$got" = "$want" ] || {
    echo "sha256 mismatch: got $got" >&2
    rm -f "$tarball"
    exit 1
  }

  rm -rf "$TOOLS/zig-$ZIG_VERSION" "$TOOLS/.zig-extract"
  mkdir -p "$TOOLS/.zig-extract"
  tar -xf "$tarball" -C "$TOOLS/.zig-extract"
  mv "$TOOLS/.zig-extract/zig-$zig_plat-$ZIG_VERSION" "$TOOLS/zig-$ZIG_VERSION"
  rm -rf "$TOOLS/.zig-extract" "$tarball"
  echo "installed zig $ZIG_VERSION ($zig_plat)"
fi

# macOS 26 SDKs ship arm64e-only libSystem.tbd targets, which zig 0.14.1
# cannot link host binaries against. Steer SDK detection to the newest
# installed SDK that still carries arm64-macos tbds (e.g. 15.4).
if [ "$uname_s" = "Darwin" ]; then
  shim="$TOOLS/bin/xcrun"
  cat >"$shim" <<'EOF'
#!/bin/sh
# Generated by tools/bootstrap.sh.
for sdk in /Library/Developer/CommandLineTools/SDKs/MacOSX15.4.sdk \
           /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk; do
  case " $* " in
    *" --show-sdk-path "*)
      [ -d "$sdk" ] && { printf '%s\n' "$sdk"; exit 0; } ;;
  esac
done
exec /usr/bin/xcrun "$@"
EOF
  chmod +x "$shim"
fi

printf 'zig: %s\n' "$("$TOOLS/zig-$ZIG_VERSION/zig" version)"
